openapi: 3.0.0
info:
  title: "Spotplay API" 
  version: 1.0.0
  description: "Una plataforma de música"
  contact:
    email: jealtzo26@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
servers:
  - url: http://localhost:4000/api/v1
    description: "Localhost"
tags:
  - name: Song
    description: "Canciones de la aplicación"
  - name: Genre
    description: "Géneros de las canciones"
  - name: Artist
    description: "Artistas"
  - name: Playlist
    description: "Lista de canciones"
  - name: User  
    description: "Usuarios de la plataforma"
  - name: Role  
    description: "Rol de cada usuario"
components:
  schemas: 
    Song:
      type: object
      properties:         
        id:
          type: integer
          format: int64
        title:
          type: string
        uri:
          type: string
        duration:
          type: string
        image:
          type: string
        idArtist:
          type: integer
          format: int64
        idGenre: 
          type: integer
          format: int64
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        email:
          type: string
        password:
          type: string
        roleId:        
          type: integer
          format: int64          
paths:
  /user/signup:
    post:
      tags:
      - User
      summary: Crear un usuario
      operationId: createUser
      description: Se creará un usuario para utilizarlo en la aplicación
      requestBody: 
        description: El atriburo role es opcional
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        require: true
      responses:
        201:
          description: "Registro exitoso"
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        400:
          description: Bad request
          content: {}          


  /user:
    get:
      summary: Todos los usuarios
      description: Regresa todos los usuarios en formato JSON
      responses:
        "200":
          description: "Responde con todos los usuarios registrados"
          content: 
            application/json:
              schema: 
                type: object
                properties: 
                  request:
                    type: string
                  error:
                    type: boolean
                  status:
                    type: integer
                  body:
                    type: array
                    items:
                      type: object
                      properties:
                        _id:
                          type: integer
                        _username:
                          type: string
                        _email:
                          type: string
                        _password:
                          type: string
                      
                        
              
  