openapi: 3.0.0
info:
  title: "Spotplay API" 
  version: 1.0.0
  description: "Una plataforma de música"
  contact:
    email: jealtzo26@gmail.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
servers:
  - url: http://localhost:4000/api/v1
    description: "Localhost"
tags:
  - name: Song
    description: "Canciones de la aplicación"
  - name: Genre
    description: "Géneros de las canciones"
  - name: Artist
    description: "Artistas"
  - name: Playlist
    description: "Lista de canciones"
  - name: User  
    description: "Usuarios de la plataforma"
  - name: Role  
    description: "Rol de cada usuario"
    
components:
  schemas: 
    Song:
      type: object
      properties:         
        title:
          type: string
        uri:
          type: string
        duration:
          type: string
        image:
          type: string
        idArtist:
          type: integer
          format: int64
        idGenre: 
          type: integer
          format: int64
          
    SongResponse:
      type: object
      properties:         
        _id:
          type: integer
          format: int64
        _title:
          type: string
        _uri:
          type: string
        _duration:
          type: string
        _image:
          type: string
        _idArtist:
          type: integer
          format: int64
        _idGenre: 
          type: integer
          format: int64
          
    User:
      type: object
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
        roleId:        
          type: integer
          format: int64
          
    UserResponse:
      type: object
      properties:
        _id:
          type: integer
          format: int64
        _username:
          type: string
        _email:
          type: string
        _password:
          type: string
        _roleId:        
          type: integer
          format: int64  
          
    UserPut:
      type: object
      properties:
        _username:
          type: string
        _email:
          type: string
        _password:
          type: string
          
paths:
  /user/signup:
    post:
      tags:
      - User
      summary: Crear un usuario
      operationId: createUser
      description: Se creará un usuario para utilizarlo en la aplicación
      requestBody: 
        description: El atriburo role es opcional
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        201:
          description: "Registro exitoso"
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        400:
          description: Bad request
        content: {}
  /user:
    get:
      tags:
      - User
      summary: Todos los usuarios
      description: Retorna todos los usuarios de la plataforma
      responses:
        200:
          description: Array de todos los usuarios
          content:
            application/json:
              schema:
                type: array
                items:
                    $ref: '#/components/schemas/UserResponse'
        400:
          description: Bad request
          content: {}
  /user/{id}:
    get:
      tags:
      - User
      summary: Usuario por id
      description: Retorna un usuario con un id específico
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
          description: ID del usuario
      responses:
        200:
          description: Usuario solicitado
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/UserResponse'
        400:
          description: Bad request
          content: {}

    put:
      tags:
      - User
      summary: Actualizar usuario
      description: Actualiza un usuario en específico
      requestBody: 
        description: Al menos uno de todos los atributos
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/UserPut'
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
          description: ID del usuario
      responses:
        200:
          description: Actualizado con éxito
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/UserResponse'
        400:
          description: Bad request
          content: {}
